apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-bzpzmgwt
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-bzpzmgwt:6daf1f091effb4128b4f03b99070991ceaf11b88@sha256:213bade2329bb1107719467c957b5d656d9e1e9ebfe12924c2086438165240fa
          name: container-image
